---
- hosts: all
  sudo: yes
  tasks:
    - name: copy /opt/kodi
      copy: src=./src/kodi dest=/opt
    - name: build kodi
      shell: bash -lc "cd /opt/kodi && docker-compose build"
    - name: chmod run.sh
      file: path=/opt/kodi/run.sh state=touch mode=0755
    - name: install kmod-alsa (testing)
      yum: name=kmod-alsa enablerepo=elrepo-testing
      when: ansible_distribution == 'CentOS' and ansible_distribution_version.split('.')[0] == '6'
